import { Contact, Interaction, AISuggestion, FollowUp, AIActivityEvent, PipelineColumn } from "@/types";

export const mockContacts: Contact[] = [
    {
        id: "c1",
        name: "Nguyễn Văn Nam",
        phone: "0912345678",
        email: "nam.nguyen@techviet.vn",
        company: "TechViet Solutions",
        tags: ["VIP", "Lọc nước", "Hệ thống"],
        channel_source: "zalo",
        stage: "negotiation",
        sentiment: "positive",
        ai_summary: "Anh Nam đang quan tâm đến hệ thống lọc nước công nghiệp 50 triệu. Đã thảo luận qua Zalo 3 lần. Hứa gửi hợp đồng cuối tuần này. Khả năng chốt cao (~85%).",
        deal_value: 50000000,
        deal_probability: 85,
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Nam",
        created_at: "2026-02-10T08:00:00Z",
        last_contact_at: "2026-02-22T15:30:00Z",
    },
    {
        id: "c2",
        name: "Trần Thị Lan",
        phone: "0987654321",
        email: "lan.tran@xaydungphu.vn",
        company: "Xây Dựng Phú Hưng",
        tags: ["Xây dựng", "B2B"],
        channel_source: "email",
        stage: "proposal",
        sentiment: "neutral",
        ai_summary: "Chị Lan hỏi về hệ thống xử lý nước thải cho công trình 200 triệu. Đã gửi báo giá 3 ngày trước, chưa có phản hồi. Cần follow-up.",
        deal_value: 200000000,
        deal_probability: 45,
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lan",
        created_at: "2026-02-15T09:00:00Z",
        last_contact_at: "2026-02-19T11:00:00Z",
    },
    {
        id: "c3",
        name: "Lê Minh Tú",
        phone: "0903456789",
        email: "tu.le@gmail.com",
        company: "Cá nhân",
        tags: ["Nhà ở", "Nhỏ lẻ"],
        channel_source: "telegram",
        stage: "lead",
        sentiment: "positive",
        ai_summary: "Anh Tú vừa inbox Telegram hỏi về máy lọc nước gia đình RO 5 triệu. AI phát hiện từ khóa 'ngân sách 5 triệu' và 'mua tháng này'. Khả năng mua cao.",
        deal_value: 5000000,
        deal_probability: 70,
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Tu",
        created_at: "2026-02-23T07:00:00Z",
        last_contact_at: "2026-02-23T08:15:00Z",
    },
    {
        id: "c4",
        name: "Phạm Đức Hùng",
        phone: "0934567890",
        email: "hung.pham@restaurant.vn",
        company: "Nhà hàng Phú Quý",
        tags: ["F&B", "Khẩn cấp"],
        channel_source: "zalo",
        stage: "qualified",
        sentiment: "urgent",
        ai_summary: "Anh Hùng cần lọc nước cho nhà hàng gấp, hệ thống hiện tại bị hỏng. Budget 20-30 triệu. AI đánh giá đây là lead HOT vì tính cấp bách cao.",
        deal_value: 25000000,
        deal_probability: 90,
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Hung",
        created_at: "2026-02-22T14:00:00Z",
        last_contact_at: "2026-02-23T09:00:00Z",
    },
    {
        id: "c5",
        name: "Võ Thị Mai",
        phone: "0956789012",
        email: "mai.vo@greentech.vn",
        company: "GreenTech Environmental",
        tags: ["Môi trường", "Dự án lớn"],
        channel_source: "email",
        stage: "won",
        sentiment: "positive",
        ai_summary: "Chị Mai đã ký hợp đồng lắp đặt hệ thống xử lý nước 150 triệu. Dự án hoàn thành tháng 3. Có khả năng giới thiệu thêm 2 đối tác.",
        deal_value: 150000000,
        deal_probability: 100,
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Mai",
        created_at: "2026-02-01T08:00:00Z",
        last_contact_at: "2026-02-20T16:00:00Z",
    },
    {
        id: "c6",
        name: "Hoàng Văn Bình",
        phone: "0978901234",
        email: "binh.hoang@coldchain.vn",
        company: "ColdChain Logistics",
        tags: ["Logistics", "Công nghiệp"],
        channel_source: "zalo",
        stage: "proposal",
        sentiment: "neutral",
        ai_summary: "Anh Bình hỏi về RO công nghiệp 80 triệu cho nhà máy lạnh. Đang so sánh với 2 đơn vị khác. AI gợi ý nhấn mạnh bảo hành và dịch vụ sau bán.",
        deal_value: 80000000,
        deal_probability: 50,
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Binh",
        created_at: "2026-02-12T10:00:00Z",
        last_contact_at: "2026-02-21T13:00:00Z",
    },
    {
        id: "c7",
        name: "Nguyễn Thị Hoa",
        phone: "0945678901",
        email: "hoa.nguyen@spa.vn",
        company: "SPA Thư Giãn Lotus",
        tags: ["Spa", "Nước tinh khiết"],
        channel_source: "telegram",
        stage: "lead",
        sentiment: "positive",
        ai_summary: "Chị Hoa vừa nhắn Telegram về máy lọc nước cho spa, cần nước tinh khiết cho liệu pháp. Budget chưa xác định. Cần tư vấn thêm.",
        deal_value: 15000000,
        deal_probability: 35,
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Hoa",
        created_at: "2026-02-23T06:30:00Z",
        last_contact_at: "2026-02-23T07:45:00Z",
    },
];

export const mockInteractions: Interaction[] = [
    {
        id: "i1",
        contact_id: "c1",
        contact_name: "Nguyễn Văn Nam",
        channel: "zalo",
        direction: "inbound",
        content: "Anh ơi, báo giá cho mình hệ thống lọc nước công nghiệp với, bên mình cần xử lý 500m3/ngày",
        ai_extracted_intent: "Yêu cầu báo giá hệ thống lọc nước công nghiệp",
        ai_extracted_amount: 50000000,
        ai_extracted_product: "Hệ thống lọc nước công nghiệp 500m3/ngày",
        sentiment_score: 0.7,
        sentiment: "positive",
        ai_action: "AI tạo Lead mới và phân loại vào cột Báo giá",
        stage_changed_to: "proposal",
        created_at: "2026-02-10T08:30:00Z",
    },
    {
        id: "i2",
        contact_id: "c1",
        contact_name: "Nguyễn Văn Nam",
        channel: "zalo",
        direction: "inbound",
        content: "Mình xem báo giá rồi, giá hợp lý đó. Nhưng muốn hỏi thêm về bảo hành và hỗ trợ kỹ thuật sau lắp đặt?",
        ai_extracted_intent: "Quan tâm đến bảo hành và hỗ trợ kỹ thuật",
        sentiment_score: 0.6,
        sentiment: "positive",
        ai_action: "AI chuyển sang giai đoạn Đàm phán",
        stage_changed_to: "negotiation",
        created_at: "2026-02-18T10:00:00Z",
    },
    {
        id: "i3",
        contact_id: "c1",
        contact_name: "Nguyễn Văn Nam",
        channel: "zalo",
        direction: "inbound",
        content: "OK anh, mình cần file hợp đồng để trình giám đốc ký duyệt. Gửi qua email cho mình nhé",
        ai_extracted_intent: "Yêu cầu hợp đồng — tín hiệu chốt deal",
        ai_extracted_date: "2026-02-28T00:00:00Z",
        sentiment_score: 0.9,
        sentiment: "positive",
        ai_action: "AI tạo nhắc nhở: Gửi hợp đồng trước 23/02",
        created_at: "2026-02-22T15:30:00Z",
    },
    {
        id: "i4",
        contact_id: "c3",
        contact_name: "Lê Minh Tú",
        channel: "telegram",
        direction: "inbound",
        content: "Bạn ơi mình cần máy lọc nước RO cho gia đình 5 người dùng, ngân sách khoảng 5 triệu, mua tháng này được không?",
        ai_extracted_intent: "Mua máy lọc nước RO gia đình",
        ai_extracted_amount: 5000000,
        ai_extracted_product: "Máy lọc nước RO gia đình",
        ai_extracted_date: "2026-02-28T00:00:00Z",
        sentiment_score: 0.8,
        sentiment: "positive",
        ai_action: "AI tạo Lead mới từ Telegram — HIGH INTENT phát hiện",
        stage_changed_to: "lead",
        created_at: "2026-02-23T08:15:00Z",
    },
    {
        id: "i5",
        contact_id: "c4",
        contact_name: "Phạm Đức Hùng",
        channel: "zalo",
        direction: "inbound",
        content: "Cứu anh với! Hệ thống lọc nước nhà hàng bị hỏng rồi, không có nước sạch nấu ăn. Cần sửa gấp hoặc thay mới được không?",
        ai_extracted_intent: "Khẩn cấp — hệ thống lọc nước hỏng, cần xử lý ngay",
        ai_extracted_amount: 25000000,
        sentiment_score: -0.3,
        sentiment: "urgent",
        ai_action: "AI gắn nhãn URGENT và đẩy lên đầu danh sách follow-up",
        stage_changed_to: "qualified",
        created_at: "2026-02-23T09:00:00Z",
    },
    {
        id: "i6",
        contact_id: "c2",
        contact_name: "Trần Thị Lan",
        channel: "email",
        direction: "inbound",
        content: "Chào anh, bên em đang có dự án xây nhà máy cần hệ thống xử lý nước thải, công suất 100 tấn/ngày. Anh có thể tư vấn không?",
        ai_extracted_intent: "Tư vấn hệ thống xử lý nước thải công nghiệp",
        ai_extracted_amount: 200000000,
        ai_extracted_product: "Hệ thống xử lý nước thải 100 tấn/ngày",
        sentiment_score: 0.5,
        sentiment: "neutral",
        ai_action: "AI tạo Lead từ Email + phân loại B2B dự án lớn",
        stage_changed_to: "lead",
        created_at: "2026-02-15T09:30:00Z",
    },
];

export const mockAISuggestions: AISuggestion[] = [
    {
        id: "s1",
        contact_id: "c1",
        contact_name: "Nguyễn Văn Nam",
        type: "follow_up",
        priority: "high",
        title: "Gửi hợp đồng cho anh Nam",
        draft_message: "Chào anh Nam! Em đã chuẩn bị xong hợp đồng hệ thống lọc nước như trao đổi. Anh xem qua và cho em phản hồi nhé. Em sẵn sàng điều chỉnh nếu cần. 🙏",
        status: "pending",
        scheduled_at: "2026-02-23T10:00:00Z",
        created_at: "2026-02-22T20:00:00Z",
    },
    {
        id: "s2",
        contact_id: "c2",
        contact_name: "Trần Thị Lan",
        type: "follow_up",
        priority: "high",
        title: "Follow-up báo giá chị Lan (3 ngày chưa phản hồi)",
        draft_message: "Chào chị Lan! Em muốn hỏi thăm về báo giá hệ thống xử lý nước thải em đã gửi trước. Chị có câu hỏi gì không ạ? Em sẵn sàng điều chỉnh theo nhu cầu của chị. Dự án bắt đầu khi nào ạ?",
        status: "pending",
        scheduled_at: "2026-02-23T08:00:00Z",
        created_at: "2026-02-22T08:00:00Z",
    },
    {
        id: "s3",
        contact_id: "c4",
        contact_name: "Phạm Đức Hùng",
        type: "call",
        priority: "high",
        title: "Gọi ngay cho anh Hùng — URGENT",
        draft_message: "Anh Hùng ơi, em thấy tin nhắn của anh. Em có thể sắp xếp kỹ thuật viên đến kiểm tra hôm nay được. Anh có thể cho em biết địa chỉ nhà hàng không ạ?",
        status: "pending",
        scheduled_at: "2026-02-23T09:30:00Z",
        created_at: "2026-02-23T09:05:00Z",
    },
    {
        id: "s4",
        contact_id: "c3",
        contact_name: "Lê Minh Tú",
        type: "quote",
        priority: "medium",
        title: "Gửi báo giá cho anh Tú",
        draft_message: "Chào anh Tú! Em có máy lọc nước RO phù hợp cho gia đình 5 người, giá 4.5 triệu, bảo hành 3 năm. Lắp đặt miễn phí trong tháng này. Anh muốn xem demo không ạ?",
        status: "pending",
        scheduled_at: "2026-02-23T14:00:00Z",
        created_at: "2026-02-23T08:20:00Z",
    },
];

export const mockFollowUps: FollowUp[] = [
    {
        id: "f1",
        contact_id: "c4",
        contact_name: "Phạm Đức Hùng",
        company: "Nhà hàng Phú Quý",
        type: "call",
        due_date: "2026-02-23T09:30:00Z",
        note: "Hệ thống lọc nước bị hỏng khẩn cấp",
        draft_message: "Anh Hùng ơi, em có thể sắp xếp kỹ thuật viên đến hôm nay được ạ?",
        status: "pending",
        ai_created: true,
        channel: "zalo",
    },
    {
        id: "f2",
        contact_id: "c1",
        contact_name: "Nguyễn Văn Nam",
        company: "TechViet Solutions",
        type: "follow_up",
        due_date: "2026-02-23T10:00:00Z",
        note: "Gửi file hợp đồng như đã hứa",
        draft_message: "Anh Nam ơi! Em đã chuẩn bị xong hợp đồng. Anh xem qua nhé.",
        status: "pending",
        ai_created: true,
        channel: "email",
    },
    {
        id: "f3",
        contact_id: "c2",
        contact_name: "Trần Thị Lan",
        company: "Xây Dựng Phú Hưng",
        type: "follow_up",
        due_date: "2026-02-23T08:00:00Z",
        note: "Follow-up báo giá 200M — 3 ngày chưa phản hồi",
        draft_message: "Chào chị Lan! Em muốn hỏi thăm về báo giá em đã gửi...",
        status: "pending",
        ai_created: true,
        channel: "email",
    },
    {
        id: "f4",
        contact_id: "c6",
        contact_name: "Hoàng Văn Bình",
        company: "ColdChain Logistics",
        type: "check_in",
        due_date: "2026-02-24T09:00:00Z",
        note: "Check-in tiến độ quyết định",
        draft_message: "Anh Bình ơi, anh đã có quyết định về hệ thống RO chưa ạ? Em có thể điều chỉnh báo giá nếu cần.",
        status: "pending",
        ai_created: true,
        channel: "zalo",
    },
    {
        id: "f5",
        contact_id: "c3",
        contact_name: "Lê Minh Tú",
        company: "Cá nhân",
        type: "quote",
        due_date: "2026-02-23T14:00:00Z",
        note: "Gửi báo giá máy lọc RO gia đình",
        draft_message: "Chào anh Tú! Em có máy RO phù hợp 4.5 triệu, bảo hành 3 năm...",
        status: "pending",
        ai_created: true,
        channel: "telegram",
    },
    {
        id: "f6",
        contact_id: "c5",
        contact_name: "Võ Thị Mai",
        company: "GreenTech Environmental",
        type: "check_in",
        due_date: "2026-02-20T09:00:00Z",
        note: "Check-in tiến độ dự án 150M",
        draft_message: "Chào chị Mai! Dự án lắp đặt đang tiến hành theo kế hoạch ạ?",
        status: "done",
        ai_created: false,
        channel: "email",
    },
];

export const mockAIActivityFeed: AIActivityEvent[] = [
    {
        id: "a1",
        timestamp: "2026-02-23T09:00:00Z",
        type: "new_lead",
        contact_name: "Phạm Đức Hùng",
        description: "AI phát hiện lead URGENT từ Zalo — nhà hàng cần hệ thống lọc nước gấp",
        channel: "zalo",
        icon: "🚨",
    },
    {
        id: "a2",
        timestamp: "2026-02-23T08:15:00Z",
        type: "new_lead",
        contact_name: "Lê Minh Tú",
        description: "AI tạo lead mới từ Telegram — phát hiện HIGH INTENT 'mua tháng này'",
        channel: "telegram",
        icon: "✨",
    },
    {
        id: "a3",
        timestamp: "2026-02-23T07:45:00Z",
        type: "new_lead",
        contact_name: "Nguyễn Thị Hoa",
        description: "AI tạo lead mới từ Telegram — Spa cần nước tinh khiết",
        channel: "telegram",
        icon: "💬",
    },
    {
        id: "a4",
        timestamp: "2026-02-22T20:00:00Z",
        type: "follow_up_created",
        contact_name: "Nguyễn Văn Nam",
        description: "AI tạo nhắc nhở: Gửi hợp đồng trước 10h sáng nay",
        channel: "zalo",
        icon: "📅",
    },
    {
        id: "a5",
        timestamp: "2026-02-22T15:30:00Z",
        type: "stage_change",
        contact_name: "Nguyễn Văn Nam",
        description: "AI chuyển anh Nam sang Đàm phán — phát hiện tín hiệu chốt deal",
        icon: "🔄",
    },
    {
        id: "a6",
        timestamp: "2026-02-22T08:00:00Z",
        type: "follow_up_created",
        contact_name: "Trần Thị Lan",
        description: "AI nhắc follow-up chị Lan — 3 ngày không phản hồi báo giá 200M",
        channel: "email",
        icon: "⏰",
    },
    {
        id: "a7",
        timestamp: "2026-02-21T17:00:00Z",
        type: "message_processed",
        contact_name: "Hoàng Văn Bình",
        description: "AI xử lý email từ anh Bình — trích xuất yêu cầu RO công nghiệp",
        channel: "email",
        icon: "🤖",
    },
];

export const mockPipelineColumns: PipelineColumn[] = [
    {
        id: "lead",
        label: "Lead",
        color: "#3b82f6",
        deals: [
            { id: "d1", contact_id: "c3", contact_name: "Lê Minh Tú", company: "Cá nhân", value: 5000000, days_in_stage: 0, last_activity: "2026-02-23T08:15:00Z", ai_confidence: 70, ai_moved: true, stage: "lead", channel: "telegram" },
            { id: "d2", contact_id: "c7", contact_name: "Nguyễn Thị Hoa", company: "SPA Lotus", value: 15000000, days_in_stage: 0, last_activity: "2026-02-23T07:45:00Z", ai_confidence: 35, ai_moved: true, stage: "lead", channel: "telegram" },
        ],
    },
    {
        id: "qualified",
        label: "Đủ điều kiện",
        color: "#a855f7",
        deals: [
            { id: "d3", contact_id: "c4", contact_name: "Phạm Đức Hùng", company: "Nhà hàng Phú Quý", value: 25000000, days_in_stage: 0, last_activity: "2026-02-23T09:00:00Z", ai_confidence: 90, ai_moved: true, stage: "qualified", channel: "zalo" },
        ],
    },
    {
        id: "proposal",
        label: "Báo giá",
        color: "#eab308",
        deals: [
            { id: "d4", contact_id: "c2", contact_name: "Trần Thị Lan", company: "Xây Dựng Phú Hưng", value: 200000000, days_in_stage: 4, last_activity: "2026-02-19T11:00:00Z", ai_confidence: 45, ai_moved: true, stage: "proposal", channel: "email" },
            { id: "d5", contact_id: "c6", contact_name: "Hoàng Văn Bình", company: "ColdChain Logistics", value: 80000000, days_in_stage: 2, last_activity: "2026-02-21T13:00:00Z", ai_confidence: 50, ai_moved: false, stage: "proposal", channel: "zalo" },
        ],
    },
    {
        id: "negotiation",
        label: "Đàm phán",
        color: "#f97316",
        deals: [
            { id: "d6", contact_id: "c1", contact_name: "Nguyễn Văn Nam", company: "TechViet Solutions", value: 50000000, days_in_stage: 5, last_activity: "2026-02-22T15:30:00Z", ai_confidence: 85, ai_moved: true, stage: "negotiation", channel: "zalo" },
        ],
    },
    {
        id: "won",
        label: "Thành công",
        color: "#10b981",
        deals: [
            { id: "d7", contact_id: "c5", contact_name: "Võ Thị Mai", company: "GreenTech Environmental", value: 150000000, days_in_stage: 22, last_activity: "2026-02-20T16:00:00Z", ai_confidence: 100, ai_moved: false, stage: "won", channel: "email" },
        ],
    },
    {
        id: "lost",
        label: "Thất bại",
        color: "#ef4444",
        deals: [],
    },
];

export const mockDashboardStats = {
    totalContacts: 47,
    activeDeals: 5,
    followUpsToday: 3,
    messagesProcessed: 128,
    monthlyRevenue: 430000000,
    conversionRate: 68,
};

export const mockPipelineFunnelData = [
    { stage: "Lead", count: 12, value: 85000000 },
    { stage: "Qualified", count: 8, value: 120000000 },
    { stage: "Báo giá", count: 6, value: 280000000 },
    { stage: "Đàm phán", count: 4, value: 195000000 },
    { stage: "Thành công", count: 3, value: 430000000 },
];

export const mockLeadSourcesData = [
    { name: "Zalo", value: 45, color: "#3b82f6" },
    { name: "Email", value: 30, color: "#10b981" },
    { name: "Telegram", value: 15, color: "#eab308" },
    { name: "Thủ công", value: 10, color: "#6b7280" },
];
